<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <Configurations>Developer - Debug;Release - Alpha;Release - Beta;Release - Final</Configurations>
    <Platforms>x64</Platforms>
    <TargetFrameworks>net48</TargetFrameworks>
    <AssemblyTitle>FC26ProfilePlugin</AssemblyTitle>
    <Product>FC26ProfilePlugin</Product>
    <Copyright>Copyright ©  2025</Copyright>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <UseWPF>true</UseWPF>
    <OutputType>Library</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Developer - Debug|x64'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\Developer\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE;FROSTY_DEVELOPER</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release - Alpha|x64'">
    <OutputPath>bin\Release\Alpha\</OutputPath>
    <DefineConstants>TRACE;FROSTY_ALPHA</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release - Beta|x64'">
    <OutputPath>bin\Release\Beta\</OutputPath>
    <DefineConstants>TRACE;FROSTY_BETA</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release - Final|x64'">
    <OutputPath>bin\Release\Final\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy /Y /I $(TargetPath) $(SolutionDir)$(OutDir)Plugins\Fifa\" />
  </Target>

  <ItemGroup>
    <ProjectReference Include="..\..\..\FrostyPlugin\FrostyCore.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\..\FrostySdk\FrostySdk.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
</Project>
