<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <Platforms>x64</Platforms>
    <TargetFrameworks>net48</TargetFrameworks>
    <AssemblyTitle>FC26ProfilePlugin</AssemblyTitle>
    <Product>FC26ProfilePlugin</Product>
    <Copyright>Copyright ©  2025</Copyright>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <UseWPF>true</UseWPF>
    <OutputType>Library</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy /Y $(TargetPath) $(SolutionDir)$(OutDir)Plugins\Fifa\" />
  </Target>

  <ItemGroup>
    <ProjectReference Include="..\..\..\FrostyPlugin\FrostyCore.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\..\FrostySdk\FrostySdk.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
</Project>
